spring.application.name=demo

# 1. Cấu hình Database ảo H2 (Chạy ngay không cần cài MySQL)
spring.datasource.url=jdbc:h2:mem:authdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# 2. Cấu hình gửi Email (Dùng Gmail SMTP để xác thực và quên mật khẩu)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# SỬ DỤNG BIẾN MÔI TRƯỜNG ĐỂ BẢO MẬT EMAIL
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 3. Cấu hình Đăng nhập Google (OAuth2)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email, profile